### ISSUE TITLE
can't install the package

### ISSUE THREAD

**Issue by abdelmalek13** [dvwright/phunspell#1]
I found in the readme there is a pip version of the package on PyPI, However, when I tried pip install it fails to find the package
![image](https://user-images.githubusercontent.com/14137755/115241907-a342f880-a121-11eb-9214-05357e206c49.png)

**Comment by dvwright** [comment]
It's there for sure https://pypi.org/project/spylls/ :)

Try this: `python -m pip install --upgrade pip`  then retry install spylls

If that doesn't work see:
https://stackoverflow.com/questions/49748063/pip-install-fails-for-every-package-could-not-find-a-version-that-satisfies/49748494#49748494
or maybe
https://bhch.github.io/posts/2017/04/fix-the-pip-error-couldnt-find-a-version-that-satisfies-the-requirement/
